CREATE TABLE favparks (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  userid INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  parkcode TEXT NOT NULL,
  statecode TEXT,
  parkname TEXT,
  rating NUMERIC,
  note TEXT,
  statename TEXT,
  activity TEXT,
  parknum NUMERIC,
  parkdata TEXT
);
